dist: trusty
sudo: true
language: cpp
before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev
  - sudo apt-get install -y  libsdl2-image-dev
  - sudo apt-get install -y  libglew-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2